# 参考 https://github.com/LibChecker/LibChecker/blob/master/.github/workflows/android.yml
name: Android CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**.json'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Check out
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Set Java version
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      # Build Gradle
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      # Get current date and time
      - name: Test1
        id: dt
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY_MM_DD HH_mm_ss_SSS"
      - run: echo COM_ID=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
      # Set version name
      - name: Retrieve version
        run: echo VERSION=$(echo v${{ steps.dt.outputs.year }}.${{ steps.dt.outputs.month }}.${{ steps.dt.outputs.day }}.${{ env.COM_ID }}) >> $GITHUB_ENV
      # Add version code
      - name: Bump version
        uses: Devofure/advance-android-version-actions@v1.4
        with:
          gradlePath: app/build.gradle
          versionName: ${{ env.VERSION }}
      - name: Write sign info
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' && github.repository == 'founchoo/GongYun-for-Android'
        run: |
          if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then
            echo releaseStorePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> gradle.properties
            echo releaseKeyAlias='${{ secrets.ALIAS }}' >> gradle.properties
            echo releaseKeyPassword='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo releaseStoreFile='${{ github.workspace }}/key.jks' >> gradle.properties
            echo ${{ secrets.SIGNING_KEY }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew -PappVerName=${{ env.VERSION }} app:assembleRelease
          APK_PATH=$(ls app/build/outputs/apk/release/*.apk)
          echo "APK path: $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./${{ env.APK_PATH }}
          asset_name: GongYun-${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive
