# Reference: https://github.com/LibChecker/LibChecker/blob/master/.github/workflows/android.yml
name: Auto release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.idea/**'
      - '.gitattributes'
      - '.github/**'
      - '.gitignore'
      - '.gitmodules'
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Skip duplicate actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

  build:
    name: Build, upload and release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set Java version
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          
      - name: Build Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
          
      - name: Get current date and time
        id: dt
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "YYYY.MM.DD.HH.mm"
          timezone-offset: -480
          
      - name: Set COM_ID
        run: |
          ID=${{ github.event.head_commit.id }}
          if [[ -z "$ID" ]]; then
            ID="xxxxxxx"
          else
            ID=$(echo $ID | head -c 7)
          fi
          echo COM_ID=$ID >> $GITHUB_ENV
        
      - name: Set VERSION_NAME
        run: echo VERSION_NAME=$(echo v${{ steps.dt.outputs.time }}.${{ env.COM_ID }}) >> $GITHUB_ENV
        
      - name: Set VERSION_CODE
        run: echo VERSION_CODE=$(echo ${{ steps.dt.outputs.milliseconds_since_epoch }} | head -c 10) >> $GITHUB_ENV
        
      - name: Override version name and code in build.gradle
        uses: Devofure/advance-android-version-actions@v1.4
        with:
          gradlePath: app/build.gradle
          versionName: ${{ env.VERSION_NAME }}
          versionCode: ${{ env.VERSION_CODE }}

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION
          
      - name: Build release APK
        run: |
          chmod +x ./gradlew
          ./gradlew app:assembleRelease
          
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Copy and rename APK
        run: cp ./${{ env.SIGNED_RELEASE_FILE }} ./GongYun-${{ env.VERSION_NAME }}.apk

      - name: Build release AAB
        id: buildRelease
        run: |
          chmod +x ./gradlew
          ./gradlew bundleRelease
        
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Copy and rename AAB
        run: cp ./${{ env.SIGNED_RELEASE_FILE }} ./GongYun-${{ env.VERSION_NAME }}.aab

      - name: Release APK and AAB
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_NAME }}
          token: ${{ secrets.RELEASE_TOKEN }}
          generate_release_notes: true
          files: |
            ./GongYun-${{ env.VERSION_NAME }}.apk
            ./GongYun-${{ env.VERSION_NAME }}.aab
